// <auto-generated />
namespace BachHoaXanh.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class up8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up8));
        
        string IMigrationMetadata.Id
        {
            get { return "202012290829084_up8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
