// <auto-generated />
namespace BachHoaXanh.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class up5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(up5));
        
        string IMigrationMetadata.Id
        {
            get { return "202012290647431_up5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
